// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.1
// source: catalog.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "catalog";

export interface PingReq {
}

export interface PingResponse {
  ok: boolean;
  serviceName: string;
  time: string;
}

export interface GetProductsReq {
  page: number;
}

export interface GetProductByIdReq {
  id: number;
}

export interface Product {
  id: number;
  name: string;
  price: number;
}

export interface ProductList {
  products: Product[];
}

export const CATALOG_PACKAGE_NAME = "catalog";

export interface CatalogServiceClient {
  getProducts(request: GetProductsReq): Observable<ProductList>;

  getProductById(request: GetProductByIdReq): Observable<Product>;

  ping(request: PingReq): Observable<PingResponse>;
}

export interface CatalogServiceController {
  getProducts(request: GetProductsReq): Promise<ProductList> | Observable<ProductList> | ProductList;

  getProductById(request: GetProductByIdReq): Promise<Product> | Observable<Product> | Product;

  ping(request: PingReq): Promise<PingResponse> | Observable<PingResponse> | PingResponse;
}

export function CatalogServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProducts", "getProductById", "ping"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CatalogService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CatalogService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CATALOG_SERVICE_NAME = "CatalogService";
